### ISSUE TITLE
java.lang.NoClassDefFoundError: net/minecraft/entity/Entity$1

### ISSUE THREAD

**Issue by Lanaess** [Corosauce/ZombieAwareness#10]
Having trouble with this mod on my server. After I installed the mod, the server's cpu ran at 99% while idle with no players connected. I logged in and was able to play about 2 minutes before the server crashed. The server will restart again fine, but now it crashes as soon as a player tries to connect. This is the error log:

Time: 11/17/16 10:54 PM
Description: Exception in server tick loop

java.lang.NoClassDefFoundError: net/minecraft/entity/Entity$1
at net.minecraft.entity.Entity.func_85029_a(Entity.java:2482)
at net.minecraft.entity.Entity.func_70020_e(Entity.java:1715)
at net.minecraft.entity.EntityList.func_75615_a(EntityList.java:175)
at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_186053_a(AnvilChunkLoader.java:597)
at net.minecraft.world.chunk.storage.AnvilChunkLoader.func_186050_a(AnvilChunkLoader.java:524)
at net.minecraft.world.chunk.storage.AnvilChunkLoader.loadEntities(AnvilChunkLoader.java:474)
at net.minecraftforge.common.chunkio.ChunkIOProvider.syncCallback(ChunkIOProvider.java:96)
at net.minecraftforge.common.chunkio.ChunkIOExecutor.tick(ChunkIOExecutor.java:150)
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:673)
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387)
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
at java.lang.Thread.run(Thread.java:745)

---------------------------------------------------------------------------------------

-- System Details --
Details:
Minecraft Version: 1.10.2
Operating System: Linux (amd64) version 4.8.6-201.fc24.x86_64
Java Version: 1.8.0_111, Oracle Corporation
Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
Memory: 329091392 bytes (313 MB) / 658223104 bytes (627 MB) up to 843382784 bytes (804 MB)
JVM Flags: 4 total; -Xmx832M -Xms256M -XX:+UseParNewGC -XX:+DisableExplicitGC
IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
FML: MCP 9.32 Powered by Forge 12.18.2.2107 11 mods loaded, 11 mods active
States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabl
UCHIJAAAA mcp{9.19} [Minecraft Coder Pack] (minecraft.jar)
UCHIJAAAA FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.2.2107-universal.jar)
UCHIJAAAA Forge{12.18.2.2107} [Minecraft Forge] (forge-1.10.2-12.18.2.2107-universal.jar)
UCHIJAAAA tnt_utilities_core{1.2.1} [TNTUtils Core] (minecraft.jar)
UCHIJAAAA coroai{v1.1.9} [coroai] (coroutil-1.10.2-1.1.9.jar)
UCHIJAAAA extendedrenderer{v1.0} [Extended Renderer] (coroutil-1.10.2-1.1.9.jar)
UCHIJAAAA configmod{v1.0} [Extended Mod Config] (coroutil-1.10.2-1.1.9.jar)
UCHIJAAAA customnpcs{1.9.0_beta} [CustomNPCs] (CustomNPCs_1.10.2_beta(30sep16).jar)
UCHIJAAAA tnt_utilities{1.2.1} [TNTUtils] (tnt_utilities-mc1.10-1.2.1.jar)
UCHIJAAAA worldedit{6.1.4} [WorldEdit] (worldedit-forge-mc1.10.2-6.1.4-dist.jar)
UCHIJAAAA zombieawareness{v1.20} [Zombie Awareness] (zombieawareness-1.10.2-1.20.jar)
Loaded coremods (and transformers):
TNTUtilities Core (tnt_utilities-mc1.10-1.2.1.jar)
ljfa.tntutils.asm.ExplosionTransformer
Profiler Position: N/A (disabled)
Player Count: 1

**Comment by PONYRYDE** [comment]
Same here in SSP while flying in creative (testing out a custom modpack). I never encountered nor can reproduce the crash without Zombie Awareness installed.

With the risk of providing disinformation I feel as if it may have something to do with mod villagers (I see too CustomNPC's mentioned above) as it seems to happen as a village appears in the distance. As for me, removing Immersive Engineering also allows me to relog but that may be just coincidence.

It has been hit and miss reproducing it in test worlds but with CoroUtil, Zombie Awareness, Immersive Engineering, Extra Utilities, Quark and AutoRegLib installed I have been able to crash several times by spawning in heaps of villagers but I have also spawned in thousands and not crashed at all.
[crash-2016-11-19_14.50.16-server.txt](https://github.com/Corosauce/ZombieAwareness/files/601316/crash-2016-11-19_14.50.16-server.txt)

**Comment by PONYRYDE** [comment]
After further testing it would seem to have been the villagers added by Immersive Engineering that were triggering the crash. If this turns out to be a bug on that end I will report it there.

As a workaround I added Structural Engineer, Electrician and Machinist to the blacklist in PlayerRulesAndLists.cfg which so far seems to have fixed it.

**Comment by PONYRYDE** [comment]
Nope, still crashing sometimes when a village is spawned. Have now set awareness_Sound to false and haven't crashed since......

**Comment by Lanaess** [comment]
In SSP I am able to play just fine with all mods loaded, no crash, no CPU usage issues.

In SMP (Server) environment is where I am having my problems. If I remove Custom NPC I can stop the crashing, but the CPU still runs at 100% (See https://github.com/Corosauce/ZombieAwareness/issues/8 for more details...)

**Comment by jprocket45** [comment]
just to let everyone know I filed this 23 days ago https://github.com/Corosauce/ZombieAwareness/issues/8 its been in discussion :) yes its def a issue with zombie awareness its been confirmed from many tests. oh nvm i see Lanaess was the one discussing it there lol

**Comment by NitroxydeX** [comment]
Can confirm this issue too.. took me a long time to find out ZA is causing this issue.

**Comment by Corosauce** [comment]
Fixed in dev a while ago (just commited now though): https://github.com/Corosauce/ZombieAwareness/commit/70cdef24b017073ef56dda88142be446704e148d

Due to some bad practices on my part I can't release this until I am finished with sandstorm release for weather2, due to some code changes in coroutil that will require me to release weather2 and zombie awareness updates at the same time.

Sorry for the delay.

**Comment by Lanaess** [comment]
I have been busy but finally found some time to work on Minecraft. After reading your post above Corosauce I built the latest ZombieAwareness commit 70cdef2 and the latest CoroUtil a678c96. They both compiled without issue and load fine in Minecraft Forge, but the max CPU issue is still present. 
Maybe I am rushing the issue and you have not completed the fix, if that is the case I apologize and will wait patiently for the solution. I just wanted to provide this information in case you believed it was fixed.

**Comment by Corosauce** [comment]
I'll keep an eye on it Lanaess, I am about to push the new build out (finally). Once v1.11.1 is out for testing, please provide a full log of the crash and not just a crash report log.

**Comment by Lanaess** [comment]
I will build and try v1.11.1 when you make it available. Question, will the new build also try to address the CPU issue on servers ( #8 )?

I know it's not easy troubleshooting issues like this. I want to thank you for your time and commitment with this great mod!

**Comment by jprocket45** [comment]
I sure hope where talking about 1.11.2 and not 1.11.1 like everyone is putting lol unless i am missing that the actual mod is 1.11.1 which then im derping....in any case just checking.

**Comment by NitroxydeX** [comment]
@jprocket45 it's just the version string from the mod. The mod is still for 1.10.2

**Comment by jprocket45** [comment]
on that case thank you and sorry about that I am hoping this processor issue does get worked out soon though it sounds like it doesn't happen all the time or to some people.... I load it up as 1 mod and it throws my server processor for a loop.  I am still holding out hope! :)

**Comment by Corosauce** [comment]
I'm hoping this issue is fixed for 1.11.1 release, extra hoping it was the cause of the high cpu usage, see https://github.com/Corosauce/ZombieAwareness/issues/8#issuecomment-270007655 for more info

Let me know if the issue stopped since 1.11.1's release

**Comment by Lanaess** [comment]
@Corosauce As discussed in #8 I have loaded the latest ZA and CoroUtil with all my mods.
Great news, they all seem to work perfectly together, one big happy family. I no longer have the crash issue stated here. 

One very interesting feature of ZA with another mod I use called CustomNPC. When a NPC is made hostile to monsters and attacks one, ZA sends the zombies after it just like a player char, lol. So city guards will have a bit more work...

**Comment by Corosauce** [comment]
Hahah, nice, love lil AI surprises like that, glad to hear its working! Closing this one off.

**Comment by Tri0de** [comment]
I know this a bit of a necro, but I am a mod developer and I too am having this same crash (with my mod, not ZombieAwareness). I've looked through the commits that have been stated to fix this bug, but I really cant find the code that directly prevented the Entity$1 bug from happening.

Any help for a desperate modder?

**Comment by Corosauce** [comment]
Recalling this from memory, it's not obvious in the crash reports that hide the whole story, but if you check the fml logs, you should see huge stacktraces where it looks like its stuck in a loop. There were some edge cases where sounds played in chunks that were not loaded, and I was blindly hooking those sounds and not considering seeing if the source area is even loaded before doing stuff. I fixed by either checking with world.isBlockLoaded or just added in more sanity checks.
